include ../Make.inc

SRC_DIR = src
INCL_DIR = $(PROJECT_ROOT)/include/gui
OBJ_DIR = $(PROJECT_ROOT)//build/gui
LIB_DIR = $(PROJECT_ROOT)/lib
TST_DIR = $(PROJECT_ROOT)/test

HEADERS = \
	$(INCL_DIR)/colors.hpp $(INCL_DIR)/context.hpp $(INCL_DIR)/event_manager.hpp \
	$(INCL_DIR)/point.hpp $(INCL_DIR)/quad.hpp $(INCL_DIR)/segment.hpp $(INCL_DIR)/triangle.hpp \
	$(INCL_DIR)/window.hpp

SRCS = \
	$(SRC_DIR)/context.cpp $(SRC_DIR)/event_manager.cpp $(SRC_DIR)/window.cpp

OBJS = \
	$(OBJ_DIR)/context.o $(OBJ_DIR)/event_manager.o $(OBJ_DIR)/window.o

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(OBJ_DIR)
	@echo "\033[33m Compiling " $@ "\033[0m"
	@$(CXX) $(CXXOPT) -I$(PROJECT_ROOT)/libgui/include -I$(INCL_DIR) -I$(OPENGLINC) -c $< -o $@

all: $(PROJECT_ROOT)/include $(LIB_DIR)/libgui.so test

$(PROJECT_ROOT)/include:
	@mkdir -p $(PROJECT_ROOT)/include
	@echo "\033[31m Copying includes\033[0m"
	@rsync -rpuE --delete  include/gui $(PROJECT_ROOT)/include/

$(LIB_DIR)/libgui.so: $(OBJS)
	@mkdir -p $(LIB_DIR)
	@echo "\033[35m Linking " $@ "\033[0m"
	@$(CXX) -shared $(CXXOPT) -L$(OPENGLLIBROOT) -o $@ $(OBJS) -lglut -lGLU -lGL 

test: $(TST_DIR)/test_rendering.exe

$(TST_DIR)/test_rendering.exe: $(LIB_DIR)/libgui.so test/test_rendering.cpp
	@mkdir -p $(TST_DIR)
	@echo "\033[34m Compiling " $@ "\033[0m"
	@$(CXX) $(CXXOPT) -I$(OPENGLINC) -L$(OPENGLLIBROOT) -L$(LIB_DIR) -I$(PROJECT_ROOT)/include -o $@ $^ -lgui -lglut -lGLU -lGL

clean:
	@rm -f $(SRC_DIR)/*~
	@rm -f $(INCL_DIR)/*~

# Les dépendances :
$(OBJ_DIR)/context.o: $(INCL_DIR)/context.hpp $(SRC_DIR)/context.cpp 
$(OBJ_DIR)/event_manager.o: $(INCL_DIR)/event_manager.hpp $(SRC_DIR)/event_manager.cpp
$(OBJ_DIR)/window.o: $(INCL_DIR)/window.hpp $(SRC_DIR)/window.cpp

.PHONY: doc $(PROJECT_ROOT)/include
