.TH "gui::triangle" 3 "Wed Jan 17 2018" "Version 0.1" "Parallel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui::triangle \- Description of a line segment\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <triangle\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtriangle\fP (const \fBpoint\fP &pt1, const \fBpoint\fP &pt2, const \fBpoint\fP &pt3)"
.br
.ti -1c
.RI "GLenum \fBgl_kind\fP ()"
.br
.ti -1c
.RI "void \fBemit\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Description of a line segment\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Parallel from the source code\&.
