.TH "gui::color::hsva" 3 "Wed Jan 17 2018" "Version 0.1" "Parallel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui::color::hsva \- HSV color model + alpha channel\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <colors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhsva\fP (const std::initializer_list< double > &lc)"
.br
.ti -1c
.RI "\fBhsva\fP (const std::initializer_list< int > &lc)"
.br
.ti -1c
.RI "\fBhsva\fP (const \fBhsva\fP &)=default"
.br
.ti -1c
.RI "\fBhsva\fP (const \fBrgba\fP &col)"
.br
.ti -1c
.RI "\fBoperator rgba\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBh\fP"
.br
.ti -1c
.RI "double \fBs\fP"
.br
.ti -1c
.RI "double \fBv\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
HSV color model + alpha channel\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Parallel from the source code\&.
