.TH "gui::color::rgba" 3 "Wed Jan 17 2018" "Version 0.1" "Parallel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui::color::rgba \- RGB color model + alpha channel\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <colors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrgba\fP (const std::initializer_list< double > &lc)"
.br
.ti -1c
.RI "\fBrgba\fP (const std::initializer_list< int > &lc)"
.br
.ti -1c
.RI "\fBrgba\fP (const \fBrgba\fP &)=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBr\fP"
.br
.ti -1c
.RI "double \fBg\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RGB color model + alpha channel\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Parallel from the source code\&.
